name: publish_app
run-name: Building and publishing static app
on:
  push:
#    tags:
#      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: control/app

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Show cwd
        run: pwd
      - name: List files
        run: ls -R
      - name: Build app
        run: npm run build
      - name: Save build artifact
        uses: actions/upload-artifact@v3
        with:
          name: app_build
          path: build
